---
title: "Data_analysis"
author: "Stephanie Thrasher"
date: "2022-12-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Delomys data set read in: 
```{r}
require(here)
dat_del = data.frame(read.csv(here('data', 'delomys.csv')))
```

Summary code chunk: 
```{r}
summary(dat_del$body_length)
summary(dat_del$body_mass)
```

Test of normality: 
```{r}
shapiro.test(dat_del$body_length)
shapiro.test(dat_del$body_mass)
```

Graphical Analysis: 
```{r fig.width=8}
plot(dat_del$body_mass, dat_del$body_length, main = 'Body Mass vs Body Length', xlab = 'Body Mass', ylab = 'Body Length')

#histograms 
par(mfrow = c(1, 2))
hist(dat_del$body_length, main = 'Body Length', xlab = 'Body Length')
hist(dat_del$body_mass, main = 'Body Mass', xlab = 'Body Mass')
```

Conditional boxplots: 
```{r fig.width=8, fig.height=12}
par(mfrow = c(3, 1))
boxplot(body_mass ~ sex, data = dat_del, main = 'Conditional Boxplot of Body Mass and Sex')
boxplot(body_mass ~ binomial, data = dat_del, main = 'Conditional Boxplot of Body Mass and Species')
boxplot(body_mass ~ sex:binomial, data = dat_del, main = 'Conditional Boxplot of Body Mass, Sex, and Species')
```

Model building: 
```{r}
fit_1 = lm(body_length ~ body_mass, data = dat_del)
fit_2 = lm(body_mass ~ sex, data = dat_del)
fit_3 = lm(body_mass ~ binomial, data = dat_del)
fit_4 = lm(body_mass ~ sex + binomial, data = dat_del)
fit_5 = lm(body_mass ~ sex * binomial, data = dat_del)
```

Get resids; 
```{r}
resids_1 = residuals(fit_1)
resids_2 = residuals(fit_2)
resids_3 = residuals(fit_3)
resids_4 = residuals(fit_4)
resids_5 = residuals(fit_5)
```

Plot hists of resids: 
```{r fig.width = 8}
par(mfrow = c(2, 3))
hist(resids_1)
hist(resids_2)
hist(resids_3)
hist(resids_4)
hist(resids_5)
```

Test normality:
```{r}
shapiro.test(resids_1)
shapiro.test(resids_2)
shapiro.test(resids_3)
shapiro.test(resids_4)
shapiro.test(resids_5)
```

Model interpretation:
Coefficient tables:
```{r}
knitr::kable(coef(summary(fit_1)))
knitr::kable(coef(summary(fit_2)))
knitr::kable(coef(summary(fit_3)))
knitr::kable(coef(summary(fit_4)))
knitr::kable(coef(summary(fit_5)))
```

ANOVA Tables:
```{r}
knitr::kable(anova(fit_1))
knitr::kable(anova(fit_2))
knitr::kable(anova(fit_3))
knitr::kable(anova(fit_4))
knitr::kable(anova(fit_5))
```

Calculate AIC: 
```{r}
AIC(fit_2)
AIC(fit_3)
AIC(fit_4)
AIC(fit_5)
```



